"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import re
import secrets
from ipaddress import IPv4Network, IPv6Network, ip_network
from pathlib import Path
from urllib.parse import urlsplit

import dj_database_url
from django.core.exceptions import ImproperlyConfigured

from observability.settings import FoundryObservabilitySettings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

def env_bool(name: str, *, default: bool) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name: str, *, default: str = "") -> list[str]:
    return [item.strip() for item in os.getenv(name, default).split(",") if item.strip()]


def env_networks(name: str) -> tuple[IPv4Network | IPv6Network, ...]:
    networks = []
    for value in env_list(name):
        try:
            network = ip_network(value, strict=True)
        except ValueError as error:
            raise ImproperlyConfigured(
                f"{name} contains an invalid IP network: {value}"
            ) from error
        if network.prefixlen == 0:
            raise ImproperlyConfigured(f"{name} must not contain a catch-all network")
        networks.append(network)
    return tuple(networks)


def env_profile_text(name: str, default: str, *, max_length: int) -> str:
    value = os.getenv(name, default)
    if not value or len(value) > max_length or "\x00" in value or "\r" in value:
        raise ImproperlyConfigured(f"{name} is invalid")
    return value


DEBUG = env_bool("DJANGO_DEBUG", default=False)
database_url = os.getenv("DATABASE_URL")

ALLIES_CLOUD_SERVICE_TOKEN = os.getenv("ALLIES_CLOUD_SERVICE_TOKEN")
if not DEBUG and not ALLIES_CLOUD_SERVICE_TOKEN:
    raise ImproperlyConfigured(
        "ALLIES_CLOUD_SERVICE_TOKEN is required when DJANGO_DEBUG is false"
    )
if not DEBUG and (
    len(ALLIES_CLOUD_SERVICE_TOKEN) < 32
    or any(character.isspace() for character in ALLIES_CLOUD_SERVICE_TOKEN)
):
    raise ImproperlyConfigured(
        "ALLIES_CLOUD_SERVICE_TOKEN must be a strong token outside debug"
    )

ALLIES_CLOUD_EVENT_DELIVERY_ENABLED = env_bool(
    "ALLIES_CLOUD_EVENT_DELIVERY_ENABLED", default=False
)
ALLIES_CLOUD_URL = os.getenv("ALLIES_CLOUD_URL")
ALLIES_CLOUD_EVENT_SERVICE_TOKEN = os.getenv("ALLIES_CLOUD_EVENT_SERVICE_TOKEN")
if ALLIES_CLOUD_EVENT_DELIVERY_ENABLED:
    if not ALLIES_CLOUD_URL or not ALLIES_CLOUD_EVENT_SERVICE_TOKEN:
        raise ImproperlyConfigured(
            "ALLIES_CLOUD_URL and ALLIES_CLOUD_EVENT_SERVICE_TOKEN are required "
            "when event delivery is enabled"
        )
    try:
        cloud_url = urlsplit(ALLIES_CLOUD_URL)
        cloud_port = cloud_url.port
    except ValueError:
        cloud_url = None
    if (
        cloud_url is None
        or cloud_url.scheme.lower() != "https"
        or not cloud_url.hostname
        or cloud_url.username is not None
        or cloud_url.password is not None
        or cloud_port is not None
        and not 0 <= cloud_port <= 65535
        or cloud_url.query
        or cloud_url.fragment
        or any(character in ALLIES_CLOUD_URL for character in "\x00\r\n")
    ):
        raise ImproperlyConfigured("ALLIES_CLOUD_URL must be an HTTPS origin")
    if len(ALLIES_CLOUD_EVENT_SERVICE_TOKEN) < 32 or any(
        character.isspace() for character in ALLIES_CLOUD_EVENT_SERVICE_TOKEN
    ):
        raise ImproperlyConfigured(
            "ALLIES_CLOUD_EVENT_SERVICE_TOKEN must be a strong token"
        )

PROFILE_PROVISIONING_PROVIDER = env_profile_text(
    "PROFILE_PROVISIONING_PROVIDER", "openai", max_length=128
)
PROFILE_PROVISIONING_MODEL = env_profile_text(
    "PROFILE_PROVISIONING_MODEL", "gpt-5.6-luna", max_length=255
)
PROFILE_PROVISIONING_BASE_URL = env_profile_text(
    "PROFILE_PROVISIONING_BASE_URL", "https://api.openai.com/v1", max_length=512
)
if not re.fullmatch(
    r"[a-z][a-z0-9+.-]{1,31}://[^\s]{1,507}",
    PROFILE_PROVISIONING_BASE_URL,
    re.IGNORECASE,
):
    raise ImproperlyConfigured("PROFILE_PROVISIONING_BASE_URL is not absolute")
profile_credential_name = env_profile_text(
    "PROFILE_PROVISIONING_CREDENTIAL_NAME", "OPENAI_API_KEY", max_length=64
)
profile_credential_ref = env_profile_text(
    "PROFILE_PROVISIONING_CREDENTIAL_REF",
    "file:///run/secrets/openai-api-key",
    max_length=224,
)
if not (
    re.fullmatch(r"[a-z][a-z0-9_-]{0,63}", profile_credential_name)
    or re.fullmatch(r"[A-Z][A-Z0-9_]{0,63}", profile_credential_name)
):
    raise ImproperlyConfigured("PROFILE_PROVISIONING_CREDENTIAL_NAME is invalid")
profile_credential_name = profile_credential_name.upper().replace("-", "_")
if profile_credential_name == "API_SERVER_KEY":
    raise ImproperlyConfigured("PROFILE_PROVISIONING_CREDENTIAL_NAME is reserved")
if not re.fullmatch(
    r"[a-z][a-z0-9+.-]{1,31}://[^\s]{1,191}",
    profile_credential_ref,
    re.IGNORECASE,
):
    raise ImproperlyConfigured("PROFILE_PROVISIONING_CREDENTIAL_REF is invalid")
if profile_credential_ref.lower().startswith(
    ("bearer ", "token=", "key=", "sk-", "api_key=")
):
    raise ImproperlyConfigured("PROFILE_PROVISIONING_CREDENTIAL_REF is invalid")
PROFILE_PROVISIONING_CREDENTIAL_REFS = {
    profile_credential_name: profile_credential_ref
}

SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    if not DEBUG or database_url:
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY is required when DJANGO_DEBUG is false or DATABASE_URL is set"
        )
    # Keep local development self-contained without sharing a signing key
    # across processes or environments. Restarts intentionally invalidate
    # development sessions and runtime lease tokens.
    SECRET_KEY = secrets.token_urlsafe(32)

ALLOWED_HOSTS = env_list(
    "DJANGO_ALLOWED_HOSTS",
    default="localhost,127.0.0.1,[::1]" if DEBUG else "",
)

if not DEBUG and not ALLOWED_HOSTS:
    raise ImproperlyConfigured(
        "DJANGO_ALLOWED_HOSTS is required when DJANGO_DEBUG is false"
    )

CSRF_TRUSTED_ORIGINS = env_list("DJANGO_CSRF_TRUSTED_ORIGINS")

TRUST_PROXY_HEADERS = env_bool("DJANGO_TRUST_PROXY_HEADERS", default=False)
TRUSTED_PROXY_NETWORKS = (
    env_networks("DJANGO_TRUSTED_PROXY_IPS") if TRUST_PROXY_HEADERS else ()
)
if TRUST_PROXY_HEADERS and not TRUSTED_PROXY_NETWORKS:
    raise ImproperlyConfigured(
        "DJANGO_TRUSTED_PROXY_IPS is required when DJANGO_TRUST_PROXY_HEADERS is true"
    )

# Wide events are stdout-first and safe by default.  Keep the six public
# values available as settings for middleware/tests while retaining one
# validated object as the runtime configuration boundary.
FOUNDRY_OBSERVABILITY = FoundryObservabilitySettings.from_env()
ALLIES_WIDE_EVENTS_ENABLED = FOUNDRY_OBSERVABILITY.enabled
ALLIES_WIDE_EVENTS_SUCCESS_SAMPLE_RATE = FOUNDRY_OBSERVABILITY.success_sample_rate
ALLIES_WIDE_EVENTS_SLOW_MS = FOUNDRY_OBSERVABILITY.slow_ms
ALLIES_WIDE_EVENTS_MAX_BYTES = FOUNDRY_OBSERVABILITY.max_bytes
ALLIES_WIDE_EVENTS_SINK_ENABLED = FOUNDRY_OBSERVABILITY.sink_enabled
ALLIES_WIDE_EVENTS_MAX_QUEUE_SIZE = FOUNDRY_OBSERVABILITY.max_queue_size


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "devtools",
    "runtime",
]

MIDDLEWARE = [
    "config.middleware.TrustedProxyHeadersMiddleware",
    "observability.middleware.WideEventMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if database_url:
    database_config = dj_database_url.parse(
        database_url,
        conn_max_age=60,
        conn_health_checks=True,
    )
    if database_config["ENGINE"].endswith("sqlite3"):
        database_config.setdefault("OPTIONS", {}).setdefault(
            "transaction_mode", "IMMEDIATE"
        )
    if database_config["ENGINE"] == "django.db.backends.postgresql":
        database_options = database_config.setdefault("OPTIONS", {})
        database_options.setdefault("connect_timeout", 5)
    DATABASES = {"default": database_config}
else:
    if not DEBUG:
        raise ImproperlyConfigured("DATABASE_URL is required when DJANGO_DEBUG is false")
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
            # Make short write transactions contend before reading rows. This
            # avoids SQLite's deferred-write upgrade race in concurrent runtime
            # event/lease operations; production PostgreSQL settings do not use
            # this SQLite-only option.
            "OPTIONS": {"transaction_mode": "IMMEDIATE"},
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

SECURE_PROXY_SSL_HEADER = (
    ("HTTP_X_FORWARDED_PROTO", "https") if TRUST_PROXY_HEADERS else None
)
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_SSL_REDIRECT = not DEBUG and TRUST_PROXY_HEADERS
SECURE_HSTS_SECONDS = 31_536_000 if SECURE_SSL_REDIRECT else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURE_HSTS_SECONDS > 0
SECURE_HSTS_PRELOAD = SECURE_HSTS_SECONDS > 0
