# Generated by Django 6.0.7 on 2026-08-07 11:14
# ruff: noqa: RUF012

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RuntimeProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ally_ref', models.CharField(max_length=255)),
                ('hermes_profile_key', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['workspace_id', 'ally_ref'],
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_ref', models.CharField(max_length=255, unique=True)),
                ('fly_app_ref', models.CharField(max_length=255)),
                ('volume_ref', models.CharField(max_length=255)),
                ('machine_ref', models.CharField(max_length=255)),
                ('machine_generation', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tenant_ref'],
            },
        ),
        migrations.CreateModel(
            name='ConversationBinding',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='conversation_binding', serialize=False, to='runtime.runtimeprofile')),
                ('cloud_conversation_ref', models.CharField(max_length=255, unique=True)),
                ('hermes_session_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('input_payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('unknown', 'Unknown')], default='queued', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='runtime.runtimeprofile')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='runtime.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('leased', 'Leased'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('unknown', 'Unknown')], default='queued', max_length=16)),
                ('machine_generation', models.PositiveIntegerField()),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='runtime.execution')),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField()),
                ('sequence', models.PositiveIntegerField()),
                ('event_type', models.CharField(max_length=128)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='runtime.attempt')),
            ],
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_digest', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('machine_generation', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('active', 'Active'), ('stopping', 'Stopping'), ('released', 'Released'), ('fenced', 'Fenced')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lease', to='runtime.attempt')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='runtime.runtimeprofile')),
            ],
        ),
        migrations.AddField(
            model_name='runtimeprofile',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='runtime.workspace'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['status', 'claimed_at'], name='rt_attempt_status_claimed_idx'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(fields=('execution', 'number'), name='runtime_attempt_execution_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.CheckConstraint(condition=models.Q(('number__gt', 0)), name='runtime_attempt_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='executionevent',
            constraint=models.UniqueConstraint(fields=('attempt', 'event_id'), name='runtime_event_attempt_event_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='executionevent',
            constraint=models.UniqueConstraint(fields=('attempt', 'sequence'), name='runtime_event_attempt_sequence_unique'),
        ),
        migrations.AddConstraint(
            model_name='executionevent',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gt', 0)), name='runtime_event_sequence_positive'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['profile', 'state', 'expires_at'], name='rt_lease_profile_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='lease',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ['active', 'stopping'])), fields=('profile',), name='runtime_lease_profile_unresolved_unique'),
        ),
        migrations.AddConstraint(
            model_name='runtimeprofile',
            constraint=models.UniqueConstraint(fields=('workspace', 'ally_ref'), name='runtime_profile_workspace_ally_unique'),
        ),
        migrations.AddConstraint(
            model_name='runtimeprofile',
            constraint=models.UniqueConstraint(fields=('workspace', 'hermes_profile_key'), name='runtime_profile_workspace_hermes_unique'),
        ),
        migrations.AddIndex(
            model_name='execution',
            index=models.Index(fields=['profile', 'status', 'created_at'], name='rt_exec_prof_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='execution',
            constraint=models.UniqueConstraint(fields=('workspace', 'idempotency_key'), name='runtime_execution_workspace_idempotency_unique'),
        ),
    ]
