# Generated by Django 6.0.7 on 2026-08-07 11:38
# ruff: noqa: RUF012

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runtime', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='runtimeprofile',
            constraint=models.CheckConstraint(condition=models.Q(('hermes_profile_key__regex', '^[a-z0-9][a-z0-9_-]{0,63}$'), models.Q(('hermes_profile_key__in', ('hermes', 'default', 'test', 'tmp', 'root', 'sudo')), _negated=True)), name='runtime_profile_hermes_key_contract'),
        ),
    ]
