# Generated by Django 6.0.7 on 2026-08-07 13:06
# ruff: noqa: RUF012

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runtime', '0002_runtimeprofile_runtime_profile_hermes_key_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='payload_digest',
            field=models.CharField(default='', editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='executionevent',
            name='payload_digest',
            field=models.CharField(default='', editable=False, max_length=64),
        ),
    ]
