# Generated by Django 6.0.7 on 2026-08-07 13:25
# ruff: noqa: RUF012

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runtime', '0003_execution_payload_digest_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='runtimeprofile',
            name='runtime_profile_hermes_key_contract',
        ),
        migrations.AddConstraint(
            model_name='runtimeprofile',
            constraint=models.CheckConstraint(condition=models.Q(('hermes_profile_key__regex', '^[a-z0-9][a-z0-9_-]{0,63}$'), models.Q(('hermes_profile_key__contains', '\n'), _negated=True), models.Q(('hermes_profile_key__contains', '\r'), _negated=True), models.Q(('hermes_profile_key__in', ('hermes', 'default', 'test', 'tmp', 'root', 'sudo')), _negated=True)), name='runtime_profile_hermes_key_contract'),
        ),
    ]
