# Generated by Django 6.0.7 on 2026-08-07 15:59
# ruff: noqa: RUF012

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runtime', '0004_remove_runtimeprofile_runtime_profile_hermes_key_contract_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='runtimeprofile',
            options={'base_manager_name': 'objects', 'ordering': ['workspace_id', 'ally_ref']},
        ),
    ]
