# Generated by Django 6.0.7 on 2026-08-07 16:27
# ruff: noqa: RUF012

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runtime', '0005_alter_runtimeprofile_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lease',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['active', 'stopping', 'released', 'fenced'])), name='runtime_lease_state_valid'),
        ),
    ]
