# Generated by Django 6.0.7 on 2026-08-08 23:34
# ruff: noqa: RUF012

from django.db import migrations, models


def normalize_legacy_workspace_rows(apps, schema_editor):
    """Normalize legacy refs before adding the idle binding constraint.

    The original schema required strings, so an unprovisioned row was often
    represented by empty strings. Complete legacy bindings that still have
    the old default generation ``0`` receive generation ``1`` because the
    old schema had no other durable generation to recover. Partial bindings
    are rejected explicitly and must be repaired before the migration can
    complete; silently deleting a provider reference would be unsafe.
    """

    workspace = apps.get_model("runtime", "Workspace")
    workspace_rows = workspace.objects.using(schema_editor.connection.alias)
    for field_name in ("fly_app_ref", "volume_ref", "machine_ref"):
        workspace_rows.filter(**{field_name: ""}).update(**{field_name: None})

    complete = (
        models.Q(fly_app_ref__isnull=False)
        & models.Q(volume_ref__isnull=False)
        & models.Q(machine_ref__isnull=False)
    )
    empty = (
        models.Q(fly_app_ref__isnull=True)
        & models.Q(volume_ref__isnull=True)
        & models.Q(machine_ref__isnull=True)
    )
    partial = workspace_rows.filter(~(complete | empty))
    if partial.exists():
        raise RuntimeError(
            "Workspace migration found partial Fly bindings; repair these rows "
            "before applying runtime 0007"
        )
    # Empty legacy rows are unprovisioned regardless of the stale generation
    # value left behind by an earlier implementation.  Reset them before the
    # all-null/positive-generation check is installed below.
    workspace_rows.filter(empty).exclude(machine_generation=0).update(
        machine_generation=0
    )
    workspace_rows.filter(complete, machine_generation=0).update(machine_generation=1)


class Migration(migrations.Migration):
    dependencies = [
        ("runtime", "0006_lease_runtime_lease_state_valid"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="provisioning_claim_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="provisioning_claim_token",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="provisioning_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="provisioning_kind",
            field=models.CharField(
                blank=True,
                choices=[("ensure", "Ensure"), ("replace", "Replace")],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="provisioning_machine_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="provisioning_phase",
            field=models.CharField(
                choices=[
                    ("idle", "Idle"),
                    ("app_ready", "App ready"),
                    ("volume_ready", "Volume ready"),
                    ("old_machine_stopped", "Old Machine stopped"),
                    ("old_machine_destroyed", "Old Machine destroyed"),
                    ("machine_created", "Machine created"),
                    ("machine_started", "Machine started"),
                    ("healthy", "Healthy"),
                    ("failed", "Failed"),
                ],
                default="idle",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="provisioning_previous_machine_ref",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="provisioning_source_generation",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="provisioning_target_generation",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="fly_app_ref",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="machine_ref",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="volume_ref",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(
            normalize_legacy_workspace_rows,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="workspace",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("fly_app_ref__isnull", True))
                    | ~models.Q(("fly_app_ref", ""))
                )
                & (
                    models.Q(("volume_ref__isnull", True))
                    | ~models.Q(("volume_ref", ""))
                )
                & (
                    models.Q(("machine_ref__isnull", True))
                    | ~models.Q(("machine_ref", ""))
                ),
                name="runtime_workspace_fly_refs_nonempty",
            ),
        ),
        migrations.AddConstraint(
            model_name="workspace",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "provisioning_phase__in",
                        [
                            "idle",
                            "app_ready",
                            "volume_ready",
                            "old_machine_stopped",
                            "old_machine_destroyed",
                            "machine_created",
                            "machine_started",
                            "healthy",
                            "failed",
                        ],
                    )
                ),
                name="runtime_workspace_provisioning_phase_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="workspace",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("provisioning_phase", "idle"), _negated=True),
                    models.Q(
                        ("machine_generation", 0),
                        ("fly_app_ref__isnull", True),
                        ("volume_ref__isnull", True),
                        ("machine_ref__isnull", True),
                    ),
                    models.Q(
                        ("machine_generation__gt", 0),
                        ("fly_app_ref__isnull", False),
                        ("volume_ref__isnull", False),
                        ("machine_ref__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="runtime_workspace_idle_binding_contract",
            ),
        ),
    ]
