# Generated by Django 6.0.7 on 2026-08-09
# ruff: noqa: RUF012

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("runtime", "0007_workspace_provisioning_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="RuntimeCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token_digest", models.CharField(max_length=64, unique=True)),
                ("machine_generation", models.PositiveIntegerField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="runtime_credentials",
                        to="runtime.workspace",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["workspace", "machine_generation", "revoked_at"],
                        name="rt_cred_ws_generation_idx",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="attempt",
            name="claim_id",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="attempt",
            name="terminal_request_digest",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="attempt",
            name="terminal_lease_digest",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="attempt",
            name="terminal_receipt",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attempt",
            name="terminal_receipt_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attempt",
            name="stopped_request_digest",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="attempt",
            name="stopped_lease_digest",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="attempt",
            name="stopped_receipt",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attempt",
            name="session_request_digest",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="attempt",
            name="session_lease_digest",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="attempt",
            name="session_receipt",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lease",
            name="claim_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="executionevent",
            name="stream_id",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="executionevent",
            name="event_type",
            field=models.CharField(max_length=64),
        ),
        migrations.RemoveConstraint(
            model_name="executionevent",
            name="runtime_event_sequence_positive",
        ),
        migrations.AddConstraint(
            model_name="executionevent",
            constraint=models.CheckConstraint(
                condition=models.Q(sequence__gt=0) & models.Q(sequence__lte=100000),
                name="runtime_event_sequence_positive",
            ),
        ),
    ]
