# Generated by Django 6.0.7 on 2026-08-26 01:03
# ruff: noqa: RUF012

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("runtime", "0010_fnd006_profile_receipts"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExecutionEventDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("envelope_bytes", models.BinaryField(max_length=65536)),
                ("byte_length", models.PositiveIntegerField()),
                ("fingerprint", models.CharField(max_length=100)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("delivering", "Delivering"),
                            ("delivered", "Delivered"),
                            ("exhausted", "Exhausted"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("delivery_attempts", models.PositiveSmallIntegerField(default=0)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("next_attempt_at", models.DateTimeField()),
                (
                    "safe_error_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="execution",
            name="cloud_ally_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="execution",
            name="cloud_binding_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="execution",
            name="cloud_conversation_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="execution",
            name="cloud_message_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="execution",
            name="cloud_workspace_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="execution",
            name="command_fingerprint",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="execution",
            name="command_id",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="execution",
            name="conversation_turn_ordinal",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="execution",
            name="source_kind",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddConstraint(
            model_name="execution",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("command_fingerprint", ""),
                    (
                        "command_fingerprint__regex",
                        "^canonical-json-sha256:v1:[0-9a-f]{64}$",
                    ),
                    _connector="OR",
                ),
                name="runtime_execution_command_fingerprint_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="execution",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("command_id__isnull", True),
                    models.Q(
                        ("cloud_workspace_id__isnull", False),
                        ("cloud_ally_id__isnull", False),
                        ("cloud_conversation_id__isnull", False),
                        ("cloud_message_id__isnull", False),
                        ("cloud_binding_id__isnull", False),
                        ("conversation_turn_ordinal__gt", 0),
                        models.Q(("command_fingerprint", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="runtime_execution_command_contract",
            ),
        ),
        migrations.AddField(
            model_name="executioneventdelivery",
            name="event",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery",
                to="runtime.executionevent",
            ),
        ),
        migrations.AddIndex(
            model_name="executioneventdelivery",
            index=models.Index(
                fields=["state", "next_attempt_at", "lease_expires_at"],
                name="rt_delivery_due_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="executioneventdelivery",
            constraint=models.UniqueConstraint(
                fields=("event", "fingerprint"),
                name="runtime_delivery_event_fingerprint_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="executioneventdelivery",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("state__in", ["pending", "delivering", "delivered", "exhausted"])
                ),
                name="runtime_delivery_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="executioneventdelivery",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("delivery_attempts__gte", 0), ("delivery_attempts__lte", 8)
                ),
                name="runtime_delivery_attempts_bounded",
            ),
        ),
        migrations.AddConstraint(
            model_name="executioneventdelivery",
            constraint=models.CheckConstraint(
                condition=models.Q(("byte_length__gt", 0), ("byte_length__lte", 65536)),
                name="runtime_delivery_bytes_bounded",
            ),
        ),
        migrations.AddConstraint(
            model_name="executioneventdelivery",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("fingerprint__regex", "^canonical-json-sha256:v1:[0-9a-f]{64}$")
                ),
                name="runtime_delivery_fingerprint_valid",
            ),
        ),
    ]
