# Generated by Django 6.0.7 on 2026-08-26
# ruff: noqa: RUF012

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("runtime", "0011_cld005_gateway"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="executionevent",
            name="runtime_event_sequence_positive",
        ),
        migrations.AddConstraint(
            model_name="executionevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("sequence__gt", 0), ("sequence__lte", 513)),
                name="runtime_event_sequence_positive",
            ),
        ),
    ]
