# Generated by Django 6.0.7 on 2026-09-04 00:25
# ruff: noqa: RUF012

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("runtime", "0014_reserve_server_terminal_sequence"),
    ]

    operations = [
        migrations.CreateModel(
            name="RuntimeIntent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("idempotency_key", models.UUIDField()),
                (
                    "intent_type",
                    models.CharField(
                        choices=[("composing_started", "Composing started")],
                        max_length=32,
                    ),
                ),
                ("received_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("delete_after", models.DateTimeField()),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("already_ready", "Already ready"),
                            ("waking", "Waking"),
                            ("ready", "Ready"),
                            ("first_provision_required", "First provision required"),
                            ("rate_limited", "Rate limited"),
                            ("failed", "Failed"),
                        ],
                        max_length=32,
                    ),
                ),
                ("coalesced_operation_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="workspace",
            name="last_speculative_start_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="ready_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="ready_boot_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="ready_generation",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="ready_start_epoch",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="runtime_last_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="runtime_operation_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="runtime_operation_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="runtime_operation_retry_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="workspace",
            name="runtime_operation_state",
            field=models.CharField(
                choices=[
                    ("idle", "Idle"),
                    ("requested", "Requested"),
                    ("starting", "Starting"),
                    ("awaiting_readiness", "Awaiting readiness"),
                    ("stopping", "Stopping"),
                ],
                default="idle",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="runtime_operation_trigger",
            field=models.CharField(
                blank=True,
                choices=[("speculative", "Speculative"), ("execution", "Execution")],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="runtime_start_epoch",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="workspace",
            name="speculative_keep_warm_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="workspace",
            index=models.Index(
                fields=["runtime_operation_state", "runtime_operation_requested_at"],
                name="rt_ws_power_requested_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workspace",
            index=models.Index(
                fields=["runtime_operation_state", "speculative_keep_warm_until"],
                name="rt_ws_power_idle_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="workspace",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "runtime_operation_state__in",
                        [
                            "idle",
                            "requested",
                            "starting",
                            "awaiting_readiness",
                            "stopping",
                        ],
                    )
                ),
                name="runtime_workspace_operation_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="workspace",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("runtime_operation_trigger__isnull", True),
                    ("runtime_operation_trigger__in", ["speculative", "execution"]),
                    _connector="OR",
                ),
                name="runtime_workspace_operation_trigger_valid",
            ),
        ),
        migrations.AddField(
            model_name="runtimeintent",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="runtime_intents",
                to="runtime.workspace",
            ),
        ),
        migrations.AddIndex(
            model_name="runtimeintent",
            index=models.Index(
                fields=["workspace", "received_at"], name="rt_intent_ws_received_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="runtimeintent",
            index=models.Index(
                fields=["delete_after"], name="rt_intent_delete_after_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="runtimeintent",
            constraint=models.UniqueConstraint(
                fields=("workspace", "idempotency_key"),
                name="runtime_intent_workspace_key_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="runtimeintent",
            constraint=models.CheckConstraint(
                condition=models.Q(("intent_type__in", ["composing_started"])),
                name="runtime_intent_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="runtimeintent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "outcome__in",
                        [
                            "already_ready",
                            "waking",
                            "ready",
                            "first_provision_required",
                            "rate_limited",
                            "failed",
                        ],
                    )
                ),
                name="runtime_intent_outcome_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="runtimeintent",
            constraint=models.CheckConstraint(
                condition=models.Q(("received_at__lt", models.F("expires_at"))),
                name="runtime_intent_expiry_after_received",
            ),
        ),
        migrations.AddConstraint(
            model_name="runtimeintent",
            constraint=models.CheckConstraint(
                condition=models.Q(("expires_at__lte", models.F("delete_after"))),
                name="runtime_intent_cleanup_after_expiry",
            ),
        ),
    ]
