# Generated by Django 6.0.7 on 2026-09-04 07:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("runtime", "0015_merge_20260904_0115"),
        ("runtime", "0015_runtime_intent_and_readiness"),
    ]

    operations = []
