# Generated by Django 6.0.7 on 2026-09-04 07:27

from typing import ClassVar

from django.db import migrations


class Migration(migrations.Migration):
    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("runtime", "0015_merge_20260904_0115"),
        ("runtime", "0015_runtime_intent_and_readiness"),
    ]

    operations: ClassVar[list] = []
