# Generated by Django 6.0.7 on 2026-09-07
# ruff: noqa: RUF012

import uuid

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):
    dependencies = [
        ("runtime", "0018_workspace_runtime_release"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="activity_revision",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="workspace",
            constraint=models.CheckConstraint(
                condition=Q(activity_revision__gte=0),
                name="runtime_workspace_activity_revision_nonnegative",
            ),
        ),
        migrations.AlterField(
            model_name="runtimeintent",
            name="intent_type",
            field=models.CharField(
                choices=[
                    ("composing_started", "Composing started"),
                    ("ally_creation_started", "Ally creation started"),
                ],
                max_length=32,
            ),
        ),
        migrations.RemoveConstraint(
            model_name="runtimeintent",
            name="runtime_intent_type_valid",
        ),
        migrations.AddConstraint(
            model_name="runtimeintent",
            constraint=models.CheckConstraint(
                condition=Q(
                    intent_type__in=["composing_started", "ally_creation_started"]
                ),
                name="runtime_intent_type_valid",
            ),
        ),
        migrations.CreateModel(
            name="ProvisioningHintDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ally_ref", models.CharField(max_length=255)),
                ("generation", models.PositiveIntegerField()),
                ("receipt_id", models.UUIDField()),
                ("occurred_at", models.DateTimeField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("delivering", "Delivering"),
                            ("delivered", "Delivered"),
                            ("exhausted", "Exhausted"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("delivery_attempts", models.PositiveSmallIntegerField(default=0)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("next_attempt_at", models.DateTimeField()),
                (
                    "safe_error_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "runtime_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provisioning_hint_deliveries",
                        to="runtime.runtimeprofile",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provisioning_hint_deliveries",
                        to="runtime.workspace",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("runtime_profile", "receipt_id"),
                        name="runtime_hint_profile_receipt_unique",
                    ),
                    models.CheckConstraint(
                        condition=Q(
                            state__in=[
                                "pending",
                                "delivering",
                                "delivered",
                                "exhausted",
                            ]
                        ),
                        name="runtime_hint_state_valid",
                    ),
                    models.CheckConstraint(
                        condition=Q(generation__gt=0),
                        name="runtime_hint_generation_positive",
                    ),
                    models.CheckConstraint(
                        condition=Q(delivery_attempts__gte=0)
                        & Q(delivery_attempts__lte=8),
                        name="runtime_hint_attempts_bounded",
                    ),
                ],
                "indexes": [
                    models.Index(
                        fields=("state", "next_attempt_at", "lease_expires_at"),
                        name="rt_hint_due_idx",
                    ),
                    models.Index(
                        fields=("workspace", "generation", "receipt_id"),
                        name="rt_hint_workspace_receipt_idx",
                    ),
                ],
            },
        ),
    ]
