# Generated by Django 6.0.7 on 2026-09-09 03:48

import uuid
from typing import ClassVar

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies: ClassVar = [
        ('runtime', '0018_workspace_runtime_release'),
    ]

    operations: ClassVar = [
        migrations.CreateModel(
            name='RoutineApprovalAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approval_request_id', models.UUIDField(unique=True)),
                ('action_attempt_id', models.UUIDField(unique=True)),
                ('generation', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('authorizing', 'Authorizing'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=24)),
                ('permission_consumed', models.BooleanField(default=False)),
                ('action_digest', models.CharField(max_length=64)),
                ('provider_idempotency_key', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('action_state', models.CharField(blank=True, choices=[('pre_dispatch', 'Pre-dispatch'), ('dispatching', 'Dispatching'), ('completed', 'Completed'), ('unknown', 'Unknown'), ('manual_reconciliation', 'Manual reconciliation')], max_length=32, null=True)),
                ('continuation', models.JSONField(blank=True, default=dict)),
                ('provider_receipt', models.JSONField(blank=True, null=True)),
                ('decision', models.CharField(blank=True, max_length=16, null=True)),
                ('decision_digest', models.CharField(blank=True, max_length=64, null=True)),
                ('created_event_id', models.UUIDField(blank=True, null=True)),
                ('created_event_sequence', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoutineCommandReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command_id', models.UUIDField(unique=True)),
                ('idempotency_key', models.UUIDField()),
                ('kind', models.CharField(max_length=64)),
                ('fingerprint', models.CharField(max_length=100)),
                ('response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoutineExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('routine_id', models.UUIDField()),
                ('routine_revision', models.PositiveIntegerField()),
                ('schedule_generation', models.PositiveIntegerField()),
                ('occurrence_id', models.UUIDField()),
                ('run_id', models.UUIDField()),
                ('scheduled_at', models.DateTimeField()),
                ('delayed', models.BooleanField(default=False)),
                ('occurrence_disposition', models.CharField(default='admitted', max_length=24)),
                ('main_conversation_id', models.UUIDField()),
                ('run_conversation_id', models.UUIDField()),
                ('cloud_binding_id', models.UUIDField()),
                ('owner_user_id', models.UUIDField()),
                ('ally_id', models.UUIDField()),
                ('title_snapshot', models.CharField(max_length=255)),
                ('execution_prompt', models.TextField()),
                ('generation', models.PositiveBigIntegerField(default=0)),
                ('fence', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('working', 'Working'), ('approval_waiting', 'Approval waiting'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='queued', max_length=24)),
                ('dispatch_receipt', models.JSONField(blank=True, default=dict)),
                ('terminal_receipt', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoutineLeaseAcquisition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordinal', models.PositiveIntegerField()),
                ('claim_id', models.UUIDField(unique=True)),
                ('token_digest', models.CharField(max_length=64, unique=True)),
                ('machine_generation', models.PositiveIntegerField()),
                ('current', models.BooleanField(default=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('claim_receipt', models.JSONField(blank=True, default=dict)),
                ('session_request_digest', models.CharField(blank=True, max_length=64, null=True)),
                ('stop_request_digest', models.CharField(blank=True, max_length=64, null=True)),
                ('terminal_request_digest', models.CharField(blank=True, max_length=64, null=True)),
                ('session_receipt', models.JSONField(blank=True, null=True)),
                ('stop_receipt', models.JSONField(blank=True, null=True)),
                ('terminal_receipt', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='lease',
            name='runtime_lease_profile_unresolved_unique',
        ),
        migrations.AddField(
            model_name='lease',
            name='scope_key',
            field=models.CharField(default='main', max_length=100),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('leased', 'Leased'), ('running', 'Running'), ('approval_waiting', 'Approval waiting'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('unknown', 'Unknown')], default='queued', max_length=16),
        ),
        migrations.AddField(
            model_name='routineapprovalaction',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routine_approval_actions', to='runtime.attempt'),
        ),
        migrations.AddField(
            model_name='routinecommandreceipt',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_command_receipts', to='runtime.workspace'),
        ),
        migrations.AddField(
            model_name='routineexecution',
            name='current_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_routine_executions', to='runtime.attempt'),
        ),
        migrations.AddField(
            model_name='routineexecution',
            name='execution',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='routine_execution', to='runtime.execution'),
        ),
        migrations.AddField(
            model_name='routineexecution',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_executions', to='runtime.runtimeprofile'),
        ),
        migrations.AddField(
            model_name='routineexecution',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_executions', to='runtime.workspace'),
        ),
        migrations.AddField(
            model_name='routineapprovalaction',
            name='routine_execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_actions', to='runtime.routineexecution'),
        ),
        migrations.AddField(
            model_name='routineleaseacquisition',
            name='lease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acquisitions', to='runtime.lease'),
        ),
        migrations.AddField(
            model_name='lease',
            name='current_acquisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_leases', to='runtime.routineleaseacquisition'),
        ),
        migrations.AddConstraint(
            model_name='lease',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ['active', 'stopping'])), fields=('profile', 'scope_key'), name='runtime_lease_profile_scope_unresolved_unique'),
        ),
        migrations.AddConstraint(
            model_name='routinecommandreceipt',
            constraint=models.UniqueConstraint(fields=('workspace', 'idempotency_key'), name='runtime_routine_command_receipt_key_unique'),
        ),
        migrations.AddIndex(
            model_name='routineexecution',
            index=models.Index(fields=['profile', 'status', 'created_at'], name='rt_routine_profile_status_idx'),
        ),
        migrations.AddIndex(
            model_name='routineexecution',
            index=models.Index(fields=['status', 'created_at'], name='rt_routine_status_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='routineexecution',
            constraint=models.UniqueConstraint(fields=('workspace', 'occurrence_id'), name='runtime_routine_workspace_occurrence_unique'),
        ),
        migrations.AddConstraint(
            model_name='routineexecution',
            constraint=models.UniqueConstraint(fields=('workspace', 'run_id'), name='runtime_routine_workspace_run_unique'),
        ),
        migrations.AddConstraint(
            model_name='routineexecution',
            constraint=models.UniqueConstraint(fields=('workspace', 'run_conversation_id'), name='runtime_routine_workspace_run_conversation_unique'),
        ),
        migrations.AddConstraint(
            model_name='routineexecution',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'working', 'approval_waiting'])), fields=('profile', 'routine_id'), name='runtime_routine_profile_active_unique'),
        ),
        migrations.AddConstraint(
            model_name='routineexecution',
            constraint=models.CheckConstraint(condition=models.Q(('routine_revision__gt', 0), ('schedule_generation__gt', 0)), name='runtime_routine_revision_generation_positive'),
        ),
        migrations.AddConstraint(
            model_name='routineexecution',
            constraint=models.CheckConstraint(condition=models.Q(('main_conversation_id', models.F('run_conversation_id')), _negated=True), name='runtime_routine_conversations_distinct'),
        ),
        migrations.AddConstraint(
            model_name='routineexecution',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['queued', 'working', 'approval_waiting', 'succeeded', 'failed', 'cancelled', 'expired'])), name='runtime_routine_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='routineapprovalaction',
            constraint=models.UniqueConstraint(fields=('routine_execution', 'action_attempt_id'), name='runtime_routine_action_attempt_unique'),
        ),
        migrations.AddConstraint(
            model_name='routineapprovalaction',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('routine_execution',), name='runtime_routine_pending_approval_unique'),
        ),
        migrations.AddConstraint(
            model_name='routineapprovalaction',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'authorizing', 'rejected', 'expired', 'cancelled'])), name='runtime_routine_approval_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='routineapprovalaction',
            constraint=models.CheckConstraint(condition=models.Q(('action_state__isnull', True), ('action_state__in', ['pre_dispatch', 'dispatching', 'completed', 'unknown', 'manual_reconciliation']), _connector='OR'), name='runtime_routine_action_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='routineleaseacquisition',
            constraint=models.UniqueConstraint(fields=('lease', 'ordinal'), name='runtime_routine_lease_acquisition_ordinal_unique'),
        ),
        migrations.AddConstraint(
            model_name='routineleaseacquisition',
            constraint=models.UniqueConstraint(condition=models.Q(('current', True)), fields=('lease',), name='runtime_routine_lease_current_unique'),
        ),
        migrations.AddConstraint(
            model_name='routineleaseacquisition',
            constraint=models.CheckConstraint(condition=models.Q(('ordinal__gt', 0)), name='runtime_routine_lease_ordinal_positive'),
        ),
    ]
