# Generated by Django 6.0.7 on 2026-09-07
# ruff: noqa: RUF012

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):
    dependencies = [
        ("runtime", "0019_activity_revision_and_hints"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReadyWorkspaceBundle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("preparing", "Preparing"),
                            ("ready", "Ready"),
                            ("assigned", "Assigned"),
                            ("evicting", "Evicting"),
                            ("evicted", "Evicted"),
                            ("failed", "Failed"),
                        ],
                        default="preparing",
                        max_length=16,
                    ),
                ),
                ("region", models.CharField(max_length=64)),
                ("release_fingerprint", models.CharField(max_length=255)),
                ("config_version", models.PositiveIntegerField(default=1)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "next_attempt_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "phase_claim_owner",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("phase_claim_until", models.DateTimeField(blank=True, null=True)),
                ("ready_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_health_at", models.DateTimeField(blank=True, null=True)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "safe_error_code",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ready_workspace_bundle",
                        to="runtime.workspace",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=Q(
                            state__in=[
                                "preparing",
                                "ready",
                                "assigned",
                                "evicting",
                                "evicted",
                                "failed",
                            ]
                        ),
                        name="ready_pool_bundle_state_valid",
                    ),
                    models.CheckConstraint(
                        condition=~Q(region=""),
                        name="ready_pool_bundle_region_nonempty",
                    ),
                    models.CheckConstraint(
                        condition=~Q(release_fingerprint=""),
                        name="ready_pool_bundle_release_nonempty",
                    ),
                    models.CheckConstraint(
                        condition=Q(config_version__gt=0),
                        name="ready_pool_bundle_config_positive",
                    ),
                    models.CheckConstraint(
                        condition=Q(attempt_count__gte=0) & Q(attempt_count__lte=5),
                        name="ready_pool_bundle_attempts_bounded",
                    ),
                    models.CheckConstraint(
                        condition=(
                            Q(
                                phase_claim_owner__isnull=True,
                                phase_claim_until__isnull=True,
                            )
                            | Q(
                                phase_claim_owner__isnull=False,
                                phase_claim_until__isnull=False,
                            )
                        ),
                        name="ready_pool_bundle_claim_consistent",
                    ),
                    models.CheckConstraint(
                        condition=(
                            Q(state="assigned", assigned_at__isnull=False)
                            | (~Q(state="assigned") & Q(assigned_at__isnull=True))
                        ),
                        name="ready_pool_bundle_assignment_timestamp",
                    ),
                    models.CheckConstraint(
                        condition=(
                            ~Q(state="ready")
                            | (
                                Q(ready_at__isnull=False)
                                & Q(expires_at__isnull=False)
                                & Q(last_health_at__isnull=False)
                            )
                        ),
                        name="ready_pool_bundle_ready_evidence",
                    ),
                ],
                "indexes": [
                    models.Index(
                        fields=["state", "region", "release_fingerprint"],
                        name="ready_pool_bundle_ready_idx",
                    ),
                    models.Index(
                        fields=["state", "next_attempt_at"],
                        name="ready_pool_bundle_due_idx",
                    ),
                ],
            },
        ),
    ]
