# Generated by Django 6.0.7 on 2026-09-09 04:00

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies: ClassVar = [
        ('runtime', '0019_routines_execution'),
    ]

    operations: ClassVar = [
        migrations.AddField(
            model_name='routineexecution',
            name='hermes_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
