# Generated by Django 6.0.7 on 2026-09-07
# ruff: noqa: RUF012

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("runtime", "0020_ready_workspace_bundle"),
    ]

    operations = [
        migrations.AddField(
            model_name="readyworkspacebundle",
            name="blank_volume_ref",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
