# Generated by Django 6.0.7 on 2026-09-08
# ruff: noqa: RUF012

import uuid

from django.db import migrations, models
from django.db.models import Q
from django.db.models.functions import Length
from django.db.models.lookups import LessThanOrEqual


class Migration(migrations.Migration):
    dependencies = [
        ("runtime", "0021_ready_bundle_blank_volume_ref"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("generation", models.PositiveIntegerField()),
                ("hermes_run_id", models.CharField(max_length=255)),
                ("hermes_approval_id", models.CharField(max_length=255)),
                ("action_kind", models.CharField(max_length=64)),
                ("action_label", models.CharField(max_length=120)),
                ("action_preview", models.TextField(max_length=16384)),
                ("expires_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("decision_recorded", "Decision recorded"),
                            ("applied", "Applied"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                            ("outcome_unknown", "Outcome unknown"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("decision", models.CharField(blank=True, max_length=7, null=True)),
                ("decision_command_id", models.UUIDField(blank=True, null=True)),
                ("decision_idempotency_key", models.UUIDField(blank=True, null=True)),
                (
                    "decision_fingerprint",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "acknowledgement_deadline_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("outcome", models.CharField(blank=True, max_length=9, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="approval_requests",
                        to="runtime.attempt",
                    ),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="approval_requests",
                        to="runtime.execution",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="approval_requests",
                        to="runtime.runtimeprofile",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="approval_requests",
                        to="runtime.workspace",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("attempt", "hermes_approval_id"),
                        name="runtime_approval_attempt_hermes_id_unique",
                    ),
                    models.CheckConstraint(
                        condition=Q(
                            (
                                "status__in",
                                [
                                    "pending",
                                    "decision_recorded",
                                    "applied",
                                    "expired",
                                    "cancelled",
                                    "outcome_unknown",
                                ],
                            )
                        ),
                        name="runtime_approval_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=Q(("generation__gte", 0)),
                        name="runtime_approval_generation_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=Q(("decision__isnull", True))
                        | Q(("decision__in", ["approve", "reject"])),
                        name="runtime_approval_decision_valid",
                    ),
                    models.CheckConstraint(
                        condition=Q(("outcome__isnull", True))
                        | Q(
                            (
                                "outcome__in",
                                ["approved", "rejected", "expired", "cancelled"],
                            )
                        ),
                        name="runtime_approval_outcome_valid",
                    ),
                    models.CheckConstraint(
                        condition=Q(("decision_fingerprint", ""))
                        | Q(
                            (
                                "decision_fingerprint__regex",
                                r"^canonical-json-sha256:v1:[0-9a-f]{64}$",
                            )
                        ),
                        name="runtime_approval_decision_fingerprint_valid",
                    ),
                    models.CheckConstraint(
                        condition=(
                            ~Q(("action_label", ""))
                            & ~Q(("action_preview", ""))
                            & LessThanOrEqual(Length("action_label"), 120)
                            & LessThanOrEqual(Length("action_preview"), 16 * 1024)
                        ),
                        name="runtime_approval_material_bounded",
                    ),
                ],
                "indexes": [
                    models.Index(
                        fields=("attempt", "status", "expires_at"),
                        name="rt_approval_attempt_state_idx",
                    ),
                    models.Index(
                        fields=("workspace", "status", "expires_at"),
                        name="rt_approval_ws_state_idx",
                    ),
                ],
            },
        ),
    ]
