# Generated by Django 6.0.7 on 2026-09-09 05:03
# ruff: noqa: RUF012

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runtime', '0020_routine_run_session'),
        ('runtime', '0022_approval_request'),
    ]

    operations = [
    ]
