# Generated by Django 6.0.7 on 2026-09-09 23:35
# ruff: noqa: RUF012

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runtime', '0023_merge_0020_routine_run_session_0022_approval_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cloud_binding_id', models.UUIDField()),
                ('cloud_message_id', models.UUIDField()),
                ('tool_call_digest', models.CharField(max_length=64)),
                ('request_digest', models.CharField(max_length=64)),
                ('manifest_digest', models.CharField(blank=True, max_length=64, null=True)),
                ('state', models.CharField(choices=[('preparing', 'Preparing'), ('frozen', 'Frozen'), ('registered', 'Registered'), ('failed', 'Failed')], default='preparing', max_length=16)),
                ('next_due_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('safe_error_code', models.CharField(blank=True, default='', max_length=64)),
                ('cloud_revision', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_intents', to='runtime.execution')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_intents', to='runtime.runtimeprofile')),
                ('source_attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publication_intents', to='runtime.attempt')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_intents', to='runtime.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['profile', 'state', 'next_due_at', 'id'], name='rt_publication_due_idx'), models.Index(fields=['workspace', 'state', 'next_due_at', 'id'], name='rt_publication_wake_idx')],
                'constraints': [models.UniqueConstraint(fields=('execution', 'tool_call_digest'), name='runtime_publication_execution_tool_unique'), models.CheckConstraint(condition=models.Q(('state__in', ['preparing', 'frozen', 'registered', 'failed'])), name='runtime_publication_state_valid'), models.CheckConstraint(condition=models.Q(('attempts__gte', 0), ('attempts__lte', 5)), name='runtime_publication_attempts_bounded'), models.CheckConstraint(condition=models.Q(('manifest_digest__isnull', True), ('manifest_digest__regex', '^[0-9a-f]{64}$'), _connector='OR'), name='runtime_publication_manifest_digest_valid'), models.CheckConstraint(condition=models.Q(('tool_call_digest__regex', '^[0-9a-f]{64}$'), ('request_digest__regex', '^[0-9a-f]{64}$')), name='runtime_publication_request_digests_valid'), models.CheckConstraint(condition=models.Q(models.Q(('manifest_digest__isnull', True), ('state', 'preparing')), models.Q(('manifest_digest__isnull', False), ('state__in', ['frozen', 'registered', 'failed'])), _connector='OR'), name='runtime_publication_state_manifest_contract')],
            },
        ),
    ]
