# Generated by Django 6.0.7 on 2026-09-10 14:36
# ruff: noqa: RUF012

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("runtime", "0025_publication_intent_retry_revision"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="publicationintent",
            name="runtime_publication_state_valid",
        ),
        migrations.RemoveConstraint(
            model_name="publicationintent",
            name="runtime_publication_state_manifest_contract",
        ),
        migrations.AlterField(
            model_name="publicationintent",
            name="state",
            field=models.CharField(
                choices=[
                    ("preparing", "Preparing"),
                    ("frozen", "Frozen"),
                    ("registered", "Registered"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                ],
                default="preparing",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="publicationintent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "state__in",
                        ["preparing", "frozen", "registered", "ready", "failed"],
                    )
                ),
                name="runtime_publication_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicationintent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("manifest_digest__isnull", True), ("state", "preparing")),
                    models.Q(
                        ("manifest_digest__isnull", False),
                        ("state__in", ["frozen", "registered", "ready", "failed"]),
                    ),
                    _connector="OR",
                ),
                name="runtime_publication_state_manifest_contract",
            ),
        ),
    ]
