# ruff: noqa: RUF012
# Generated by Django 6.0.7 on 2026-09-10 14:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("runtime", "0024_enable_mnemosyne_memory_defaults"),
        ("runtime", "0026_publication_ready"),
    ]

    operations = []
