# Generated by Django 6.0.7 on 2026-09-10 22:47

from typing import ClassVar

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar = [
        ("runtime", "0027_merge_20260910_1653"),
    ]

    operations: ClassVar = [
        migrations.AddField(
            model_name="runtimeprofile",
            name="cleanup_attempt_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="runtimeprofile",
            name="cleanup_previous_attempt_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="runtimeprofile",
            name="cleanup_requires_quiescence",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="DeletedProfile",
            fields=[
                ("profile_id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="runtime.workspace",
                    ),
                ),
            ],
        ),
    ]
