# Generated by Django 6.0.7 on 2026-09-12
from typing import ClassVar

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):
    dependencies: ClassVar = [
        ("runtime", "0028_profile_deletion"),
    ]

    operations: ClassVar = [
        migrations.AlterField(
            model_name="workspace",
            name="runtime_operation_trigger",
            field=models.CharField(
                blank=True,
                choices=[
                    ("speculative", "Speculative"),
                    ("execution", "Execution"),
                    ("onboarding", "Onboarding"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.RemoveConstraint(
            model_name="workspace",
            name="runtime_workspace_operation_trigger_valid",
        ),
        migrations.AddConstraint(
            model_name="workspace",
            constraint=models.CheckConstraint(
                condition=Q(
                    ("runtime_operation_trigger__isnull", True),
                    (
                        "runtime_operation_trigger__in",
                        ["speculative", "execution", "onboarding"],
                    ),
                    _connector="OR",
                ),
                name="runtime_workspace_operation_trigger_valid",
            ),
        ),
        migrations.AlterField(
            model_name="readyworkspacebundle",
            name="state",
            field=models.CharField(
                choices=[
                    ("preparing", "Preparing"),
                    ("ready", "Ready"),
                    ("parking", "Parking"),
                    ("sleeping", "Sleeping"),
                    ("assigned", "Assigned"),
                    ("evicting", "Evicting"),
                    ("evicted", "Evicted"),
                    ("failed", "Failed"),
                ],
                default="preparing",
                max_length=16,
            ),
        ),
        migrations.RemoveConstraint(
            model_name="readyworkspacebundle",
            name="ready_pool_bundle_state_valid",
        ),
        migrations.AddConstraint(
            model_name="readyworkspacebundle",
            constraint=models.CheckConstraint(
                condition=Q(
                    (
                        "state__in",
                        [
                            "preparing",
                            "ready",
                            "parking",
                            "sleeping",
                            "assigned",
                            "evicting",
                            "evicted",
                            "failed",
                        ],
                    )
                ),
                name="ready_pool_bundle_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="readyworkspacebundle",
            constraint=models.CheckConstraint(
                condition=(
                    ~Q(state__in=["parking", "sleeping"])
                    | (
                        Q(blank_volume_ref__isnull=False)
                        & Q(ready_at__isnull=False)
                        & Q(expires_at__isnull=False)
                        & Q(last_health_at__isnull=False)
                    )
                ),
                name="ready_pool_bundle_sleep_evidence",
            ),
        ),
    ]
