# Generated by Django 6.0.7 on 2026-09-24 19:02
# ruff: noqa: RUF012

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runtime', '0030_profile_compression_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='runtimeprofile',
            name='model_override',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
