# Generated by Django 6.0.7 on 2026-09-25 23:32
# ruff: noqa: RUF012

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("runtime", "0032_platform_layer_soul"),
    ]

    operations = [
        migrations.AddField(
            model_name="executioneventdelivery",
            name="sequence_gap_since",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
