"""Provider boundary for durable Foundry workspace provisioning.

The modules in this package contain provider-neutral records and protocols.
Transport adapters (for example, Fly's REST API) belong in a separate module
and must translate to these records before reaching lifecycle services.
"""

from .domain import (
    App,
    AppRecord,
    AppSpec,
    ContainerFileSecret,
    ContainerSpec,
    ContainerState,
    Machine,
    MachineHealth,
    MachineRecord,
    MachineSpec,
    MachineState,
    OpaqueReference,
    OwnershipMetadata,
    Volume,
    VolumeMount,
    VolumeRecord,
    VolumeSpec,
)
from .errors import (
    AttachmentConflictError,
    InvalidConfigurationError,
    OwnershipError,
    ProviderAttachmentConflictError,
    ProviderCapacityError,
    ProviderConflictError,
    ProviderError,
    ProviderFailure,
    ProviderInvalidConfigurationError,
    ProviderNotFoundError,
    ProviderOwnershipError,
    ProviderProtocolError,
    ProviderRateLimitError,
    ProviderRetryableError,
    ProviderTerminalError,
    ProviderTimeoutError,
    ProviderUnauthorizedError,
    ProviderUnsupportedTopologyError,
    RateLimitError,
    RetryableProviderError,
    TerminalProviderError,
)
from .fake import (
    DeterministicFakeTransport,
    FakeFlyTransport,
    FakeTransport,
    FakeTransportCall,
)
from .fly import (
    FlyHttpProvider,
    FlyProvider,
    FlyProviderAdapter,
    WorkspaceResourceNames,
    deterministic_app_name,
    deterministic_machine_name,
    deterministic_resource_names,
    deterministic_volume_name,
)
from .fly_http import (
    DEFAULT_API_BASE_URL,
    REQUEST_TIMEOUT_SECONDS,
    FlyHttpClient,
    FlyTransport,
    TransportResponse,
    UrllibFlyTransport,
)
from .protocol import FlyProviderProtocol, Provider, WorkspaceProvider

__all__ = [
    "DEFAULT_API_BASE_URL",
    "REQUEST_TIMEOUT_SECONDS",
    "App",
    "AppRecord",
    "AppSpec",
    "AttachmentConflictError",
    "ContainerFileSecret",
    "ContainerSpec",
    "ContainerState",
    "DeterministicFakeTransport",
    "FakeFlyTransport",
    "FakeTransport",
    "FakeTransportCall",
    "FlyHttpClient",
    "FlyHttpProvider",
    "FlyProvider",
    "FlyProviderAdapter",
    "FlyProviderProtocol",
    "FlyTransport",
    "InvalidConfigurationError",
    "Machine",
    "MachineHealth",
    "MachineRecord",
    "MachineSpec",
    "MachineState",
    "OpaqueReference",
    "OwnershipError",
    "OwnershipMetadata",
    "Provider",
    "ProviderAttachmentConflictError",
    "ProviderCapacityError",
    "ProviderConflictError",
    "ProviderError",
    "ProviderFailure",
    "ProviderInvalidConfigurationError",
    "ProviderNotFoundError",
    "ProviderOwnershipError",
    "ProviderProtocolError",
    "ProviderRateLimitError",
    "ProviderRetryableError",
    "ProviderTerminalError",
    "ProviderTimeoutError",
    "ProviderUnauthorizedError",
    "ProviderUnsupportedTopologyError",
    "RateLimitError",
    "RetryableProviderError",
    "TerminalProviderError",
    "TransportResponse",
    "UrllibFlyTransport",
    "Volume",
    "VolumeMount",
    "VolumeRecord",
    "VolumeSpec",
    "WorkspaceProvider",
    "WorkspaceResourceNames",
    "deterministic_app_name",
    "deterministic_machine_name",
    "deterministic_resource_names",
    "deterministic_volume_name",
]
